<?php
include( 'angel_plyoutube.inc' );

/*
 * Implemet hook block_info
 */

function angel_plyoutube_block_info() {
  $blocks = array();

  //---
  $playlists = ap_getListPlaylist();
  foreach( $playlists AS $key => $value ){
    $blocks[ $value['blockName'] ] = array(
      'info' => t('AG :: Bloque :: Videos del Playlist Youtube para '.ucfirst( $key ).'.'),
    );
  }
  //---
  $users = ap_getListUsers();
  $i = 0;
  foreach( $users AS $user ){
    if( $i > 0 ) break;

    $blocks[ $user ] = array(
      'info' => t('AG :: Bloque :: Videos del Usuario "'.$user.'" en Youtube.'),
    );

    $i++;
  }
  //---
  $videos = ap_getListVideos();
  $i = 0;
  foreach( $videos AS $video ){
    //if( $i > 0 ) break;

    $blocks[ $video ] = array(
      'info' => t('AG :: Bloque :: Videos al azar con grandes visitas. ['.$video.']"'),
    );

    $i++;
  }
  //---
  $ct = ap_getContentTypes();
  foreach( $ct AS $type ){
    $blocks[ 'ct_'.$type ] = array(
      'info' => t('AG :: Bloque :: Videos del Tipo de Contenido [' . $type . ']'),
    );
  }

  /*
  $type = 'music';
  $blocks[ 'ct_'.$type ] = array(
    'info' => t('AG :: Bloque :: Videos del Tipo de Contenido [' . $type . ']'),
  );
  $type = 'trailer';
  $blocks[ 'ct_'.$type ] = array(
    'info' => t('AG :: Bloque :: Videos del Tipo de Contenido [' . $type . ']'),
  );
  */
  //---

  $names_nodequeue = ap_getNameNodequeue();
  foreach( $names_nodequeue AS $item ){
    $blocks[ 'nn_'.$item ] = array(
      'info' => t('AG :: Bloque :: Videos del Nodequeue [' . 'nn_'.$item . ']'),
    );
  }

  $item = 'test';
  $blocks[ 'nn_'.$item ] = array(
    'info' => t('AG :: Bloque :: Videos del Nodequeue [' . 'nn_'.$item . ']'),
  );

  return $blocks;
}
/*
 * Implemet hook block_view
 */

function angel_plyoutube_block_view($delta = '') {
  $block = array();

  //---
  $playlists = ap_getListPlaylist();
  foreach( $playlists AS $key => $value ){

    switch ($delta) {
      //----------
      case $value['blockName']:
        $data = angel_plYoutube_getPlVideos( $value['playlistKey'] );
        $block['content'] = theme($value['blockName'], array('nodes'=>$data));
        break;
      //----------
    }

  }
  //---
  $users = ap_getListUsers();
  $i = 0;
  foreach( $users AS $user ){
    if( $i > 0 ) break;

    switch ($delta) {
      //----------
      case $user:
        $data = angel_plYoutube_getVideosUser( $user );
        $block['content'] = theme($user, array('nodes'=>$data));
        break;
      //----------
    }

    $i++;
  }
  //---
  $videos = ap_getListVideos();
  $i = 0;
  foreach( $videos AS $video ){
    //if( $i > 0 ) break;

    switch ($delta) {
      //----------
      case $video:
        $data = angel_plYoutube_getVideo( $video );
        $block['content'] = theme($video, array('nodes'=>$data));
        break;
      //----------
    }

    $i++;
  }
  //---
  $ct = ap_getContentTypes();

  foreach( $ct AS $type ){
    if( $delta == 'ct_'.$type ){
      $data = angel_plYoutube_getHtmlVideosCT( $type );
      $block['content'] = theme('ct_'.$type, array('nodes'=>$data));
      break;
    }
  }

  /*
  $type = 'music';
  $data = angel_plYoutube_getHtmlVideosCT( $type );
  $block['content'] = theme('ct_' . $type, array('nodes'=>$data));
  $type = 'trailer';
  $data = angel_plYoutube_getHtmlVideosCT( $type );
  $block['content'] = theme('ct_' . $type, array('nodes'=>$data));
  */
  //---

  //---
  $names_nodequeue = ap_getNameNodequeue();
  foreach( $names_nodequeue AS $item ){

    switch ($delta) {
      //----------
      case 'nn_'.$item:
        $data = angel_plYoutube_getHtmlVideosNN( $item );
        $block['content'] = theme('nn_'.$item, array('nodes'=>$data));
        break;
      //----------
    }

  }
  //---


  $item = 'test';
  switch ($delta) {
    //----------
    case 'nn_'.$item:
      $data = angel_plYoutube_getHtmlVideosNNT( 'music' );
      $block['content'] = theme('nn_'.$item, array('nodes'=>$data));
      break;
    //----------
  }


  return $block;
}

/*
 * Implemet hook_theme
 */

function angel_plyoutube_theme( $existing, $type, $theme, $path ) {
  $items = array();

  //---
  $playlists = ap_getListPlaylist();
  foreach( $playlists AS $key => $value ){
    $items[ $value['blockName'] ] = array(
      'template' => 'templates/angel_plyoutube_bloque_playlist',
      'variables'=>array('nodes'=>NULL),
    );
  }
  //---
  $users = ap_getListUsers();
  $i = 0;
  foreach( $users AS $user ){
    if( $i > 0 ) break;

    $items[ $user ] = array(
      'template' => 'templates/angel_plyoutube_bloque_playlist',
      'variables'=>array('nodes'=>NULL),
    );

    $i++;
  }
  //---
  $videos = ap_getListVideos();
  $i = 0;
  foreach( $videos AS $video ){
    $items[ $video ] = array(
      'template' => 'templates/angel_plyoutube_bloque_playlist',
      'variables'=>array('nodes'=>NULL),
    );

    $i++;
  }
  //---
  $ct = ap_getContentTypes();
  foreach( $ct AS $ctType ){
    $items[ 'ct_'.$ctType ] = array(
      'template' => 'templates/angel_plyoutube_bloque_playlist',
      'variables'=>array('nodes'=>NULL),
    );
  }
  /*
  $type = 'music';
  $items[ 'ct_' . $type ] = array(
    'template' => 'templates/angel_plyoutube_bloque_playlist',
    'variables'=>array('nodes'=>NULL),
  );
  $type = 'trailer';
  $items[ 'ct_' . $type ] = array(
    'template' => 'templates/angel_plyoutube_bloque_playlist',
    'variables'=>array('nodes'=>NULL),
  );
  */
  //---

  $names_nodequeue = ap_getNameNodequeue();
  foreach( $names_nodequeue AS $item ){
    $items[ 'nn_'.$item ] = array(
      'template' => 'templates/ag_nodequeue',
      'variables'=>array('nodes'=>NULL),
    );
  }


  $item = 'test';
  $items[ 'nn_'.$item ] = array(
    'template' => 'templates/ag_nodequeue',
    'variables'=>array('nodes'=>NULL),
  );

  return $items;
}
