<?php
drupal_add_css( drupal_get_path('module', 'ag_custom_block').'/css/ag_custom_block.css', array('group' => CSS_DEFAULT, 'type' => 'file') );

/*
 * Implemet hook block_info
 */

function ag_custom_block_block_info() {
  $blocks = array();
  //---
    $blocks[ 'ag_custom_block_css' ] = array(
      'info' => t('AG :: Bloque :: Estilos custom del site.'),
    );
  //---
  return $blocks;
}

/*
 * Implemet hook block_view
 */

function ag_custom_block_block_view($delta = '') {
  $block = array();
  //---
  $block['content'] = theme('ag_custom_block_css', array('nodes'=>array()));
  //---
  return $block;
}

/*
 * Implemet hook_theme
 */

function ag_custom_block_theme( $existing, $type, $theme, $path ) {
  $items = array();
  //---
    $items['ag_custom_block_css'] = array(
      'template' => 'templates/ag_custom_block_css',
      'variables'=>array('nodes'=>NULL),
    );
  //---
  return $items;
}
