<?php

// ESTO ES PURO FORMALISMO. LAS LIBRERIAS SE ENCUENTRAN EN EL DIRECTORIO 'lib'.
include 'lib/isOnline.php';
include 'lib/toolShareCount.php';

class HelpTools{

	//---------------
	function __construct(){

	}
	//---------------

	//---------------
	public function isOnLine( $uri = NULL ){
		$status = FALSE;

		if(!is_null( $uri )){
			$tool = new IsOnline();
			$status = $tool ->statusSite( $uri );
		}

		return $status;
	}
	//---------------

	//---------------
	public function isOnLineSN( $social_network = NULL ){
		$status = TRUE;

		$tool = new IsOnline();
		if( !is_null( $social_network ) )
			$status = $tool -> statusSocialSite( $social_network );
		else
			$status = $tool -> statusAllSocialSite();

		return $status;
	}
	//---------------

}




// +++++++++++++++++++++++
// +++++++++++++++++++++++
// +++++++++++++++++++++++



//----------
function r360_helptools_block_info() {

  $blocks['block_helptools'] = array(
    'info' => t('Bloque :: Help Tools'),
  );

  return $blocks;
}
//----------


//----------
function r360_helptools_block_view($delta = '') {
  $block = array();
  $block['content'] = '';

  switch ($delta) {

    //----------
    case 'block_helptools':
      $block['subject'] = 'Bloque :: Help Tools';
      
      //$data = r360_helptools_loadSN();
      //$data = r360_helptools_loadSN( 'http://www.facebook.com' );
      //$data = r360_helptools_loadSN( 'http://api.facebook.com' );
      $data = r360_helptools_loadSN();
      //$data = r360_helptools_loadSN( 'http://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.0' );
      
      $block['content'] = theme('block_helptools', array('nodes' => $data));
      break;
    //----------

  }

  return $block;
}
//----------


//----------
function r360_helptools_theme( $existing, $type, $theme, $path ) {
  $items = array();

  $items['block_helptools'] = array(
    'variables' => array('nodes' => NULL),
    'template' => 'templates/r360_helptools'
  );

  return $items;
}
//----------


//----------
function r360_helptools_loadSN( $url = NULL ){
	
	$tool = new HelpTools();
	if( !is_null( $url ) ){
		if( $tool -> isOnLine( $url ) )
			return ( $url.' isOnline' );
		else
			return ( $url.' isNotOnLine' );
	}
	else{
		if( $tool -> isOnLineSN() )
			return ( 'Todos isOnline' );
		else
			return ( 'Nadie isOnLine' );
	}
}
//----------
